# Generated by Django 4.2.9 on 2024-02-05 10:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('notes_app', '0002_notecategory_alter_note_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='notes_app.notecategory'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='note',
            name='search_text',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
