# Generated by Django 4.2.9 on 2024-02-05 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes_app', '0004_alter_note_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='search_text',
        ),
    ]
